In [1]:
import time
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Slicing and dicing

In [5]:
a[2,2]

9

In [6]:
a[:,2]

array([3, 6, 9])

In [7]:
a[2,:]

array([7, 8, 9])

In [8]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

## Metadata

In [9]:
a.shape #Rows, cols

(3, 3)

In [10]:
a.dtype

dtype('int64')

## Assignment

In [11]:
a[1,1] = 99
a

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

## Broadcasting

In [14]:
a[0,:] = 42
a

array([[42, 42, 42],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [15]:
a[:,0] * a[:,1]

array([1764,  396,   56])

In [16]:
a[:,0] + a[:,1]

array([ 84, 103,  15])

## Transposing

In [17]:
a.T

array([[42,  4,  7],
       [42, 99,  8],
       [42,  6,  9]])

In [18]:
b = np.array([100,1000,10000])
b

array([  100,  1000, 10000])

In [19]:
b.T

array([  100,  1000, 10000])

In [20]:
a * b.T

array([[  4200,  42000, 420000],
       [   400,  99000,  60000],
       [   700,   8000,  90000]])

In [ ]:
## Missing values

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]).astype(np.single)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [22]:
a[0,0] = None
a

array([[nan,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [23]:
mask1 = np.isnan(a)
mask1

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

## Boolean masks

In [24]:
a[mask1]

array([nan], dtype=float32)

In [25]:
~mask1

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
a[~mask1]

array([2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [27]:
mask2 = (a%2 == 0)
mask2

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [28]:
mask3 = mask1 | mask2
mask3

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True, False]])

## Scaling up

In [29]:
c = np.linspace(start=0, stop=1_000, num=10_000_000)
c

array([0.0000000e+00, 1.0000001e-04, 2.0000002e-04, ..., 9.9999980e+02,
       9.9999990e+02, 1.0000000e+03])

In [31]:
c = c.reshape((-1, 10))
c

array([[0.00000000e+00, 1.00000010e-04, 2.00000020e-04, ...,
        7.00000070e-04, 8.00000080e-04, 9.00000090e-04],
       [1.00000010e-03, 1.10000011e-03, 1.20000012e-03, ...,
        1.70000017e-03, 1.80000018e-03, 1.90000019e-03],
       [2.00000020e-03, 2.10000021e-03, 2.20000022e-03, ...,
        2.70000027e-03, 2.80000028e-03, 2.90000029e-03],
       ...,
       [9.99997100e+02, 9.99997200e+02, 9.99997300e+02, ...,
        9.99997800e+02, 9.99997900e+02, 9.99998000e+02],
       [9.99998100e+02, 9.99998200e+02, 9.99998300e+02, ...,
        9.99998800e+02, 9.99998900e+02, 9.99999000e+02],
       [9.99999100e+02, 9.99999200e+02, 9.99999300e+02, ...,
        9.99999800e+02, 9.99999900e+02, 1.00000000e+03]])

In [32]:
c.shape

(1000000, 10)

## Aggregation functions

In [34]:
c.mean(axis=0)

array([499.99955, 499.99965, 499.99975, 499.99985, 499.99995, 500.00005,
       500.00015, 500.00025, 500.00035, 500.00045])

In [35]:
c.mean(axis=1)

array([4.50000045e-04, 1.45000015e-03, 2.45000025e-03, ...,
       9.99997550e+02, 9.99998550e+02, 9.99999550e+02])

In [37]:
c.mean(axis=None)

499.9999999999999

In [39]:
c.std(axis=0)

array([288.67516346, 288.67516346, 288.67516346, 288.67516346,
       288.67516346, 288.67516346, 288.67516346, 288.67516346,
       288.67516346, 288.67516346])

In [40]:
c.max(axis=0)

array([ 999.9991,  999.9992,  999.9993,  999.9994,  999.9995,  999.9996,
        999.9997,  999.9998,  999.9999, 1000.    ])

## Sampling "randomly" generated data

In [42]:
rng = np.random.default_rng(seed=1337)

In [43]:
unif = rng.uniform(size=1_000_000).reshape((1_000,-1))
unif

array([[0.8781019 , 0.18552796, 0.92090045, ..., 0.72794008, 0.8937005 ,
        0.81058111],
       [0.1375034 , 0.38642542, 0.39805364, ..., 0.75937242, 0.87265145,
        0.22746494],
       [0.47078207, 0.03034535, 0.54588502, ..., 0.74048304, 0.87665908,
        0.04906525],
       ...,
       [0.25369797, 0.13674861, 0.13290901, ..., 0.2703767 , 0.89503146,
        0.32989024],
       [0.88795843, 0.87938783, 0.96860779, ..., 0.17029483, 0.9823097 ,
        0.51758375],
       [0.40936224, 0.2872502 , 0.6123626 , ..., 0.74569434, 0.11553701,
        0.70179987]])

In [49]:
norm = rng.normal(size=10_000_000).reshape(1_000, -1)
norm

array([[ 1.5258859 ,  1.8670051 , -0.16517146, ...,  0.22906062,
        -0.48327244, -0.30926583],
       [ 0.65153916,  0.86647241, -0.07155768, ...,  1.43064447,
         0.67949202, -0.96383389],
       [ 1.79547187, -1.76648268,  0.46626309, ...,  1.35177437,
         0.75600519, -0.22698251],
       ...,
       [-1.15089474, -0.02559881, -0.97609605, ...,  0.06756403,
        -1.22020049,  0.87597973],
       [ 1.10783905, -0.44369456,  1.73745396, ..., -0.48819666,
        -1.21001165, -0.01178629],
       [ 0.95675804, -0.17131706,  2.15961373, ...,  0.49559705,
         0.66259315,  1.44802192]])

## Oppgave
Ta tiden det tar å multiplisere 1 million tilfeldig genererte tall med hverandre - kontra å gjøre det samme med iterasjon i python. Du kan bruke norm fra over som utgangspunkt. 
 

In [50]:
for j in range(20):
    #Python
    start = time.time()
    multiplisert = []
    for i in norm:
        multiplisert.append(i*i)
    end = time.time()
    print(f"Took {str(round(end-start, 10))} seconds")

Took 0.0573368073 seconds
Took 0.0486719608 seconds
Took 0.0424165726 seconds
Took 0.0422854424 seconds
Took 0.0422379971 seconds
Took 0.0450093746 seconds
Took 0.0434207916 seconds
Took 0.0428352356 seconds
Took 0.0425248146 seconds
Took 0.0421390533 seconds
Took 0.0444293022 seconds
Took 0.0444746017 seconds
Took 0.0424449444 seconds
Took 0.0424573421 seconds
Took 0.0424306393 seconds
Took 0.0446221828 seconds
Took 0.0446681976 seconds
Took 0.0433573723 seconds
Took 0.0425183773 seconds
Took 0.0424237251 seconds


In [51]:
for j in range(20):
    #Numpy
    start = time.time()
    norm * norm
    end = time.time()
    print(f"Took {str(round(end-start, 10))} seconds")

Took 0.0657849312 seconds
Took 0.039024353 seconds
Took 0.0234231949 seconds
Took 0.0173606873 seconds
Took 0.0149943829 seconds
Took 0.0147194862 seconds
Took 0.0145366192 seconds
Took 0.0145158768 seconds
Took 0.0145173073 seconds
Took 0.015547514 seconds
Took 0.0162642002 seconds
Took 0.0145525932 seconds
Took 0.0161941051 seconds
Took 0.0166568756 seconds
Took 0.014737606 seconds
Took 0.0146863461 seconds
Took 0.0144712925 seconds
Took 0.0144841671 seconds
Took 0.0144946575 seconds
Took 0.0146422386 seconds
